# currently only using Ansible to deploy on control node
web_server:
  hosts:
    archie:
      ansible_user: martin
      ansible_host: archie.zapto.org
      ansible_python_interpreter: /home/martin/kaita/archie-server/ansible/av/bin/python3
      ansible_port: 1917
      # cap std +1
      ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36393964656138386661333130623934353337623034326236306464396362653364616530393937
          3033393562353838373137353935656165373966653561380a366263633138323935643163633239
          64326661633730333132323863356435623734323331393863356439356330626464343264376362
          3730343337353764350a616537353235633033646366653761366237393336303533643263313632
          6463